apiVersion : batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    project: django
spec:
  template:
    spec:
      containers:
      - name: django-migrate
        image: django_app
        command: ["./manage.py", "migrate"]
        envFrom:
          - configMapRef:
              name: django-app-config
        imagePullPolicy: IfNotPresent
      restartPolicy: Never

